### ISSUE TITLE
Does not import from Sketch Toolbox

### ISSUE THREAD

**Issue by jshmllr** [sketchpacks/bug-reports#15]
**Platform:**
**Sketchpacks for macOS Version: 10.12.4**

### Current Behavior
No import

### Expected Behavior
Import

### Workaround
Don't use this application

**Comment by demersdesigns** [comment]
@jshmllr It looks like Sketch Toolbox changed their data model causing Sketchpack's import process to break. It's referenced in issue #11.

**Comment by adamkirkwood** [comment]
@jshmllr Hey there. Unfortunately, @demersdesigns is correct.

What once was working, no longer works with their latest changes to prune old plugins.

The tough decision here is either (1) we keep the feature to import from Sketch Toolbox even if it doesn't work for more than half, _or_ we remove the feature and the few who would benefit lose out?

As of right now, we're deciding to keep it to serve the few.

**Comment by bomberstudios** [comment]
@adamkirkwood Sketch Toolbox is dead. Any change you may have seen in the data format is definitely me working on `plugin-directory` (while trying not to make Sketch Toolbox explode, which is increasingly hard for a dead project :P )

How can I help you with the data model?

**Comment by jshmllr** [comment]
Thank you all for the feedback. From a user perspective, killing the import menu option entirely sounds like the best option since it's not working 100% - probably not even 1%. If I had never known about the import as a user, I would've have submitted this request. _My 2¢._ I'll close this ticket. Thanks Sketchpacks folks!

**Comment by bomberstudios** [comment]
Ping @sketchpacks, this should be fixable but I need more details about what the actual problem is

**Comment by adamkirkwood** [comment]
@jshmllr We won't be spending much more efforts in terms of importing Sketch Toolbox as we near our`v0.6.0` release as we've gone a different approach to the problem.

@bomberstudios A fix for Sketch Toolbox would be great, but once `v0.6.0` it won't matter so much. 

What happens when I re-opened Sketch Toolbox after the big purge to the plugin repository, my Sketch Toolbox SQLite db somehow stopped being correct. It no longer showed what plugins I had installed via ST.

**Comment by bomberstudios** [comment]
Cool, will unsubscribe from the issue then : )
