### ISSUE TITLE
Wrong version of "User Flows"

### ISSUE THREAD

**Issue by ghost** [sketchpacks/bug-reports#17]
**Platform: OS X**
**Sketchpacks for macOS Version: 10.11.6**

### Steps to reproduce
Install "User Flows"

### Current behavior
Installs v1.0

### Expected behavior
Should install v2.0.4 as shown in sketchpacks

**Comment by demersdesigns** [comment]
@moarliman My guess here is that even though the default branch is v2, which lists version 2.0.4 in it's manifest.json, Sketchpacks is pulling from the master branch which lists version 1.0 in it's manifest.json.

**Comment by willdavis** [comment]
@demersdesigns  you are correct. The issue was that Sketchpacks was hard coded to listen to the `master` branch. 

We have updated the API to track default branches now. So any future change like this should be picked up by Sketchpacks.

_**Please note**: If the plugin is not integrated with Sketchpacks Relay, it may take up to a day for the changes to be visible in the registry._

@moarliman  I have double checked and Sketchpacks is now correctly delivering`User Flows` at version `2.0.4`

**Comment by demersdesigns** [comment]
Awesome. Thanks for the update @willdavis!
