### ISSUE TITLE
Text search returns seemingly random results instead of 0 results

### ISSUE THREAD

**Issue by mludowise** [sketchpacks/bug-reports#32]
**Platform:** OS X 10.12.5
**Sketchpacks for macOS Version:** 0.57

### Steps to reproduce
Search for "runner" in SketchPacks (or via the API: http://api.sketchpacks.com/v1/plugins?text=runner).

### Current behavior
Returns 10 results, none of which use the word "runner" anywhere in their name or description. Loading the API result in a browser and doing a find on "runner" returns 0 results.

### Expected behavior
Should return 0 results since no plugins contain the word "runner"

### Workaround
None.

**Comment by willdavis** [comment]
this is actually behaving as designed.
the `?text=` parameter uses a full-text search across the plugins `manifest` and `README.md`

the plugins returned by that search all have the text 'runner' inside their readmes. from the Sketch Runner badge.

for example:
https://api.sketchpacks.com/v1/plugins/com.betterthantomorrow.sketch.distributor/readme

The README.md text is weighted lower than the manifest text, but if no plugins have that info in the manifest, then the ones with it in the readme will be shown.

full-text search is not very helpful for small search strings.  This is where partial searches will shine.

**Comment by willdavis** [comment]
Linking this to: https://github.com/sketchpacks/feedback/issues/31 for more info

**Comment by startmyquest** [comment]
Hi, I think I am experiencing what I think this original poster was reporting. Is there a way to increase the weighting for the title of the plugin. I tried searching for the exact name of the plugin I was looking for and was surprised not to get this as a result at all in the top 10.

**Steps to reproduce**

Typed in "Symbol instance sheet" - only 10 results returned are: Fluid, Maketch, Style Inventory, Sketch data populator, Sandro's Sketch Plugins, Auto-layout by Anima, iOS path Exporter, Duplicator, Find and Replac, Sync

Typed in "Sketch runner" - only 10 results returned are: Sketch Measure, Fluid, WeSektch, Sketch data populatr, Sketch constraints, UserFlows, Rename it, Sketch Material, Sketch I18N, Auto-layout by Anima, 

Typed in "Symbol states" - only 10 results returned are:  Fluid, Maketch, Style Inventory, Sketch data populator, Sandro's Sketch Plugins, Auto-layout by Anima, Compo. Duplicator, Find and Replace, Sync

**Current Behaviour**

Search returns a small list of 10 results, of which there are 6-8 common overlapping results for three different search terms. Is impossible to use search to find a a plugin by its name.

**Expected Behaviour**

The top results, should be weighted towards matching plugin name first, their description, then other full search text. So that I see those with closest match first.

I expect to see more than 10 results from the search if they exist.

**Work around**

If you're looking for specific plugin, browse the popular and newest menus to see if you can spot them there. Or scroll through the A to Z till you get to them. If they begin with S.... you've got a long way to go.
