### ISSUE TITLE
[API] versions_count is sometimes 0

### ISSUE THREAD

**Issue by mludowise** [sketchpacks/bug-reports#33]
**Platform:** API
**API Version:** v1

### Steps to reproduce
Go to https://api.sketchpacks.com/v1/plugins/com.mludowise.sketch-plugin-manager

### Current behavior
`versions_count` is 0

### Expected behavior
`versions_count` should be 1 because there is 1 version in the appcast file.

### Workaround
Interpret 0 as 1.

**Comment by willdavis** [comment]
Thanks for pointing this out.  It looks like there is a bug in the background job that keeps plugin releases up-to-date.

The `versions_count` should be `5` since you have 5 Github releases.  The versions endpoint is showing correctly, so it must be a problem with the cache counter not being incremented correctly.

https://api.sketchpacks.com/v1/plugins/com.mludowise.sketch-plugin-manager/versions

**Comment by willdavis** [comment]
The `versions_count` counter cache is now correctly updating when versions are added/removed.

Please note that the counter is tracking the number of releases in the repository. If there are no releases, the `versions_count` will show as 0, but the Appcast will still have 1 version, the HEAD commit.

I think i'll add some flag so its easier to tell if the plugin is using releases or commits for versioning.
If the plugin is using commits for versioning, the appcast will only ever have 1 version in it.

**Comment by mludowise** [comment]
If the only way to get multiple versions in the appcast is to use github release, perhaps a better name for the field would be `releases_count`, which would eliminate the need for a flag. Then I think it's a clearer implication that if `releases_count == 0` then only HEAD is available.
